# https://www.freecodecamp.org/news/publishing-github-event-data-with-github-actions-and-pages/
# https://stackoverflow.com/questions/58597010/how-to-access-a-github-issue-comment-body-using-github-actions
# This is a basic workflow to help you get started with Actions
# https://github.com/maguowei/iaas/blob/d48834c18b66ae0f3ae32e5e62a6811dfddadcb2/.github/workflows/iaas.yml

name: issue2post
description: "Turn issues into markdown file"
inputs:
  branch:
    description: "Target branch name to push the markdownfile"
    required: true
    default: "master"
  dir:
    description: "the posts dir"
    required: true
    default: "_posts"
  GITHUB_TOKEN:
    description: "secrets.GITHUB_TOKEN"
    required: true
  created_at:
    description: "github.event.issue.created_at"
    required: true
  title:
    description: "github.event.issue.title"
    required: true
  body:
    description: "github.event.issue.body"
    required: true
  actor:
    description: "github.actor"
    required: true
outputs:
  markdown-file:
    description: "The generated markdown file"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - id: generate-markdown-file
      name: Turn comment into file
      shell: bash
      run: |
        DATE="${{ inputs.created_at }}"
        mkdir -p ${{ inputs.dir }}
        cat <<'EOF' > _posts/${DATE:0:10}-${{ inputs.title }}.md
        ---
        layout: post
        title: ${{ inputs.title }}
        date: ${{ inputs.created_at }}
        ---
        ${{ inputs.body }}
        EOF
        echo "::set-output name=markdown-file::$(echo ${{ inputs.body }})"
    - name: Push changes to repo
      shell: bash
      run: |
        REMOTE=https://${{ inputs.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git config user.email "${{ inputs.actor }}@users.noreply.github.com"
        git config user.name "${{ inputs.actor }}"
        git pull ${REMOTE}
        git checkout ${{ inputs.branch }}
        git add .
        git status
        git commit -am "Add new comment"
        git push ${REMOTE} ${{ inputs.branch }}
